#!/bin/bash
# Written by Yiheng Hu (2026.3.12)
# Module: Atlas ROI Extraction and Native Space Mapping
#
# ==============================================================================
# IMPORTANT WARNING: 
# Ensure that the spatial resolution of the external Atlas provided as input 
# strictly matches the MNI templates used in this script (e.g., both 2mm or 
# both 1mm isotropic). Mixing resolutions will lead to interpolation misalignment 
# and inaccurate ROI extraction in native space.
# ==============================================================================
export FSLOUTPUTTYPE=NIFTI

# ==============================================================================
# Input Validation
# ==============================================================================
# Require at least 3 arguments: T1_dir, Atlas_dir, and at least 1 ROI index
if [ "$#" -lt 3 ]; then
    echo "Usage: $0 <work_dir> <atlas_dir> <roi_index_1> [roi_index_2 ...]"
    exit 1
fi

MNI_BRAIN="/home/wanglab/fsl/data/standard/MNI152_T1_2mm_brain.nii.gz"

cd $1
ATLAS=$2

# Shift by 1 to consume work_dir and atlas_dir. The rest are ROI indices.
shift 2
ROI_INDICES=("$@")

echo "=== Starting ROI Extraction Module (ANTs Hybrid) ==="
echo ">> Target ROIs Index: ${ROI_INDICES[*]}"

# ==============================================================================
# Step 1: Core Registration (T1 to MNI using ANTs SyNQuick)
# ==============================================================================
echo ">> Calculating Non-linear Registration (T1 <-> MNI) using ANTs..."
# Note: ANTs uses raw_T1_brain.nii.gz generated by HD-BET in the previous script.
antsRegistrationSyNQuick.sh -d 3 -f "$MNI_BRAIN" -m raw_T1_brain.nii.gz -o tmp_ANTs_T1_to_MNI_

# ANTs generates inverse mapping files: 
# tmp_ANTs_T1_to_MNI_1InverseWarp.nii.gz (Non-linear)
# tmp_ANTs_T1_to_MNI_0GenericAffine.mat (Linear)

# ==============================================================================
# Step 2: Determine FSL Transform Strategy (T1 -> EPI)
# ==============================================================================
echo ">> Checking FSL T1-to-EPI transformation files..."
if [ -f "T1_to_distorted_EPI_warp.nii" ]; then
    STRATEGY="FIELDMAP"
    echo "   -> Fieldmap detected. Will use FSL non-linear warp for T1 -> EPI."
elif [ -f "raw_T1_brain_to_EPI.mat" ]; then
    STRATEGY="LINEAR"
    echo "   -> No fieldmap detected. Will use FSL linear matrix for T1 -> EPI."
else
    echo "   -> ERROR: Missing FSL mapping files from proc_raw.sh."
    exit 1
fi

# ==============================================================================
# Step 3: Loop Through and Process All ROIs
# ==============================================================================
echo ">> Processing ROIs..."

for ROI_INDEX in "${ROI_INDICES[@]}"; do
    echo "   ---------------------------------------"
    echo "   -> Extracting and mapping ROI: $ROI_INDEX"
    
    # 1. Extract current ROI from the MNI Atlas
    fslmaths "$ATLAS" -thr "$ROI_INDEX" -uthr "$ROI_INDEX" -bin tmp_MNI_ROI_${ROI_INDEX}.nii
    
    # 2. Project ROI from MNI to Native T1 Space (Using ANTs Inverse transforms)
    # Note: NearestNeighbor (-n) is CRITICAL to keep ROI mask binary (0 and 1)
    antsApplyTransforms -d 3 -i tmp_MNI_ROI_${ROI_INDEX}.nii \
                        -r raw_T1_brain.nii.gz \
                        -o tmp_T1_ROI_${ROI_INDEX}.nii \
                        -t [tmp_ANTs_T1_to_MNI_0GenericAffine.mat, 1] \
                        -t tmp_ANTs_T1_to_MNI_1InverseWarp.nii.gz \
                        -n NearestNeighbor
                        
    # 3. Project ROI from Native T1 Space to Native EPI Space (Using FSL transforms)
    if [ "$STRATEGY" == "FIELDMAP" ]; then
        applywarp --ref=MC_Templ.nii \
                  --in=tmp_T1_ROI_${ROI_INDEX}.nii \
                  --warp=T1_to_distorted_EPI_warp.nii \
                  --interp=nn \
                  --out=native_EPI_ROI_${ROI_INDEX}_mask.nii
    else
        flirt -in tmp_T1_ROI_${ROI_INDEX}.nii \
              -ref MC_Templ.nii \
              -applyxfm -init raw_T1_brain_to_EPI.mat \
              -interp nearestneighbour \
              -out native_EPI_ROI_${ROI_INDEX}_mask.nii
    fi
    echo "   -> Completed mapping for ROI: $ROI_INDEX"
done

# ==============================================================================
# Cleanup
# ==============================================================================
echo ">> Cleaning up intermediate files..."
rm tmp_*.nii 2>/dev/null
rm tmp_*.mat 2>/dev/null
rm tmp_ANTs* 2>/dev/null

echo "=== ROI Extraction Completed ==="