#!/bin/bash
# Written by Yiheng Hu (2026.3.20)

# ==========================================
# 1. hardcore settings
# ==========================================
bids_out_dir="/mnt/c/rtfmri/nii_files/BIDS"
config_file="/mnt/c/rtfmri/batch/bids/config.json"
sub_id='sub-01'

# ==========================================
# 2. Get User Input
# ==========================================
echo "-----------------------------------------------"
echo "
Real-time transferred .dcm files will be stored as follow ways:
C:.
│
├─20260317.20260317_RT_02.2026.03.17_10_02_07_STD_1.3.12.2.1107.5.99.3
│  │  001_000013_000001_1.3.12.2.1107.5.2.43.166305.2026031710390810723723103.dcm
│  │  001_000013_000002_1.3.12.2.1107.5.2.43.166305.2026031710390985117823169.dcm
│  │  001_000013_000003_1.3.12.2.1107.5.2.43.166305.2026031710391185117823242.dcm
│  │  001_000013_000004_1.3.12.2.1107.5.2.43.166305.2026031710391385119723315.dcm
│  │
│  ├─15-online-practice
"
echo -n "Please input the Windows path of transferred .dcm files:"
read -r dcm_path
dcm_path=$(wslpath -u "$dcm_path")
echo "So it's in: ${dcm_path}"

echo "-----------------------------------------------"
echo "
File structure of exported DICOM database is like:
C:.
│  DICOMDIR
│
└─DICOM
    └─26031703
        ├─19350000
        │      11933663
        │      ...
        │
        └─24130000
                14148086
                ...
"
echo -n "Please enter the Windows path of exported DICOM files: "
read -r dicom_bin_path
dicom_bin_path=$(wslpath -u "$dicom_bin_path")
echo "So it's in: ${dicom_bin_path}"
echo "-----------------------------------------------"

# ==========================================
# 3. Merge Data into Temporary Directory
# ==========================================
echo "Creating temporary directory and merging DICOM files..."
temp_dicom_dir=$(mktemp -d)

# Copy both datasets into the single temporary directory
cp -r "$dcm_path"/* "$temp_dicom_dir"/
cp -r "$dicom_bin_path"/* "$temp_dicom_dir"/

# ==========================================
# 3.5 Scaffold BIDS Root Files
# ==========================================
mkdir -p "$bids_out_dir"

if [ ! -f "$bids_out_dir/dataset_description.json" ]; then
    echo "Generating dataset_description.json..."
    cat <<EOF > "$bids_out_dir/dataset_description.json"
{
    "Name": "Real-time fMRI Project",
    "BIDSVersion": "1.8.0",
    "DatasetType": "raw",
    "License": "CC0",
    "Authors": [
        "Yiheng Hu"
    ]
}
EOF
fi

if [ ! -f "$bids_out_dir/README" ]; then
    echo "Generating README..."
    echo "This dataset is generated by dcm2bids pipeline." > "$bids_out_dir/README"
fi

# ==========================================
# 4. Execute dcm2bids
# ==========================================
echo "Starting dcm2bids conversion for sub-${sub_id}..."
dcm2bids -d "$temp_dicom_dir" -p "$sub_id" -c "$config_file" -o "$bids_out_dir"

# ==========================================
# 5. Cleanup
# ==========================================
echo "Conversion finished. Cleaning up temporary files..."
rm -rf "$temp_dicom_dir"
rm -rf "$bids_out_dir/tmp_dcm2bids"

echo "Done! Subject ${sub_id} processed successfully. Check ${bids_out_dir}"
